name: learndao_bot
description: Web3 teacher bot.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'


dependencies:
  teledart: ^0.3.4
  logging: ^1.0.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
